// ── Daily health digests (notification center) ──────────────────
//
// One digest per client per day, generated by the cron dispatcher right
// after the sync fan-out. body stores STRUCTURE, not copy — the bell panel
// renders it per viewer language, so wording changes never touch stored
// rows. Failures here must never sink the cron: the dispatcher wraps the
// whole call, and each client is additionally isolated below.

import { createAdminSupabase } from "./supabase/admin";
import { computeMetrics } from "./metrics";
import { runSanityChecks } from "./diagnostics";
import { todayKL, formatDateParam, parseDateParam } from "./dates";
import type { DailyMetric } from "./types";
import type { TrackedMetrics } from "./sheets";

export type DigestSeverity = "info" | "warn" | "error";

export interface DigestBody {
  sync: { status: "success" | "error" | "missing"; error?: string };
  kpi_error?: string;
  changes: { count: number; months: string[] };
  quarantine: number;
  anomaly?: { metric: "cpl"; value: number; baseline: number };
  sanity: string[];
}

export interface DigestInputs {
  syncStatus: "success" | "error" | "missing";
  syncError?: string | null;
  kpiError?: string | null;
  changes: { count: number; months: string[] };
  quarantineAdded: number;
  anomaly: { metric: "cpl"; value: number; baseline: number } | null;
  sanity: string[];
}

/** Pure severity + body assembly — exported for tests. */
export function buildClientDigest(i: DigestInputs): { severity: DigestSeverity; body: DigestBody } {
  const body: DigestBody = {
    sync: { status: i.syncStatus, ...(i.syncError ? { error: i.syncError } : {}) },
    ...(i.kpiError ? { kpi_error: i.kpiError } : {}),
    changes: i.changes,
    quarantine: i.quarantineAdded,
    ...(i.anomaly ? { anomaly: i.anomaly } : {}),
    sanity: i.sanity,
  };
  const severity: DigestSeverity =
    i.syncStatus !== "success" ? "error"
    : i.anomaly || i.quarantineAdded > 0 || i.sanity.length > 0 || i.kpiError ? "warn"
    : "info";
  return { severity, body };
}

/**
 * CPL spike test — pure, exported for tests. Yesterday's CPL more than
 * `factor`× the trailing-30-day CPL, with a small-denominator guard
 * (yesterday inquiry >= 5) so one stray lead can't cry wolf.
 */
export function detectCplAnomaly(
  yesterdayRows: DailyMetric[],
  baselineRows: DailyMetric[],
  funnelType: string,
  factor = 1.5,
): { metric: "cpl"; value: number; baseline: number } | null {
  if (yesterdayRows.length === 0 || baselineRows.length === 0) return null;
  const y = computeMetrics(yesterdayRows, funnelType);
  const b = computeMetrics(baselineRows, funnelType);
  if (y.inquiry < 5 || b.cpl <= 0 || y.cpl <= 0) return null;
  if (y.cpl > b.cpl * factor) {
    return { metric: "cpl", value: Math.round(y.cpl * 100) / 100, baseline: Math.round(b.cpl * 100) / 100 };
  }
  return null;
}

const METRIC_FIELDS = [
  "ad_spend", "lead_funnel_spend", "branding_spend", "inquiry", "contact",
  "appointment", "est_showup", "showup", "orders", "sales",
] as const;

function toMetric(r: Record<string, unknown>): DailyMetric {
  return {
    date: parseDateParam(String(r.date))!,
    ad_spend: Number(r.ad_spend), lead_funnel_spend: Number(r.lead_funnel_spend),
    branding_spend: Number(r.branding_spend), inquiry: Number(r.inquiry),
    contact: Number(r.contact), appointment: Number(r.appointment),
    est_showup: Number(r.est_showup), showup: Number(r.showup),
    orders: Number(r.orders), sales: Number(r.sales),
  };
}

/** Sum same-date rows across brands (same semantics as the read adapter). */
function mergeByDate(rows: Record<string, unknown>[]): DailyMetric[] {
  const byDate = new Map<string, DailyMetric>();
  for (const r of rows) {
    const key = String(r.date);
    const m = toMetric(r);
    const existing = byDate.get(key);
    if (existing) {
      for (const f of METRIC_FIELDS) existing[f] = existing[f] + m[f];
    } else {
      byDate.set(key, m);
    }
  }
  return Array.from(byDate.values());
}

/** Generate today's digest for every client. Per-client isolation: one bad
 *  client logs and moves on. Idempotent (upsert on client_id+day+kind). */
export async function generateDailyDigests(
  clients: { id: string; name: string }[],
  db: ReturnType<typeof createAdminSupabase> = createAdminSupabase(),
): Promise<void> {
  const today = todayKL();
  const dayKey = formatDateParam(today);
  const since24h = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
  const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1);
  const windowStart = new Date(yesterday); windowStart.setDate(yesterday.getDate() - 30);
  const monthStart = new Date(today.getFullYear(), today.getMonth(), 1);

  for (const c of clients) {
    try {
      const [runRes, changesRes, quarRes, rowsRes, statesRes] = await Promise.all([
        db.from("sync_runs")
          .select("status, error, stats")
          .eq("client_id", c.id).gte("started_at", today.toISOString())
          .order("started_at", { ascending: false }).limit(1).maybeSingle(),
        db.from("data_changes")
          .select("metric_date")
          .eq("client_id", c.id).gt("detected_at", since24h).limit(500),
        db.from("quarantine_rows")
          .select("id", { count: "exact", head: true })
          .eq("client_id", c.id).gt("created_at", since24h),
        db.from("daily_metrics")
          .select("brand, date, ad_spend, lead_funnel_spend, branding_spend, inquiry, contact, appointment, est_showup, showup, orders, sales")
          .eq("client_id", c.id)
          .gte("date", formatDateParam(windowStart)).lte("date", formatDateParam(yesterday))
          .order("date").limit(1000),
        db.from("brand_states")
          .select("tab_name, funnel_type, tracked")
          .eq("client_id", c.id),
      ]);

      const run = runRes.data;
      const stats = (run?.stats ?? null) as { kpi_error?: string } | null;

      const months = new Set<string>();
      for (const ch of changesRes.data ?? []) months.add(String(ch.metric_date).slice(0, 7));

      const states = (statesRes.data ?? []).sort((a, b) => String(a.tab_name).localeCompare(String(b.tab_name)));
      const funnelType = states.length ? String(states[states.length - 1].funnel_type) : "appointment";
      const tracked: TrackedMetrics = states.length
        ? states
            .map((s) => (s.tracked ?? { appointment: false, est_showup: false, showup: false }) as TrackedMetrics)
            .reduce((a, b) => ({ appointment: a.appointment || b.appointment, est_showup: a.est_showup || b.est_showup, showup: a.showup || b.showup }))
        : { appointment: true, est_showup: true, showup: true };

      const merged = mergeByDate(rowsRes.data ?? []);
      const yKey = formatDateParam(yesterday);
      const yesterdayRows = merged.filter((r) => formatDateParam(r.date) === yKey);
      const baselineRows = merged.filter((r) => formatDateParam(r.date) !== yKey);
      const mtdRows = merged.filter((r) => r.date >= monthStart);

      const sanity = mtdRows.length
        ? runSanityChecks(computeMetrics(mtdRows, funnelType), tracked, funnelType === "walkin" ? "walkin" : "appointment").map((s) => s.code)
        : [];

      const { severity, body } = buildClientDigest({
        syncStatus: run ? (run.status === "success" ? "success" : "error") : "missing",
        syncError: run?.error ? String(run.error) : null,
        kpiError: stats?.kpi_error ?? null,
        changes: { count: (changesRes.data ?? []).length, months: [...months].sort() },
        quarantineAdded: quarRes.count ?? 0,
        anomaly: detectCplAnomaly(yesterdayRows, baselineRows, funnelType),
        sanity,
      });

      const { error } = await db.from("notifications").upsert({
        client_id: c.id, day: dayKey, kind: "daily_digest", severity, body,
        created_at: new Date().toISOString(),
      }, { onConflict: "client_id,day,kind" });
      if (error) throw new Error(error.message);
    } catch (err) {
      console.error(`digest failed for ${c.name}:`, err instanceof Error ? err.message : err);
    }
  }
}
